# Generated by Django 5.1.2 on 2025-01-18 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaderboard',
            old_name='username',
            new_name='name',
        ),
    ]
