services:
  proxy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - transcendance

  backend:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - transcendance

volumes:
  caddy_data:
  caddy_config:


networks:
  transcendance:
    driver: bridge
