services:
  backend:
    build: ./backend
    restart: unless-stopped
    expose:
      - "8000" # Only expose to internal network
    volumes:
      - ./backend:/app/
    networks:
      - internal

  frontend:
    build: ./frontend
    restart: unless-stopped
    expose:
      - "3000" # Only expose to internal network
    volumes:
      - ./frontend:/app/
    networks:
      - internal
    depends_on:
      - backend

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    depends_on:
      - backend
      - frontend

networks:
  internal:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
