services:
  backend:
    build: ./apps/backend
    restart: unless-stopped
    ports:
      - '8000:8000'
    volumes:
      - ./apps/backend:/app/

  frontend:
    build: ./apps/frontend
    restart: unless-stopped
    ports:
      - '5173:5173'
    volumes:
      - ./apps/frontend:/app/
    depends_on:
      - backend

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./apps/proxy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
      - frontend

volumes:
  caddy_data:
  caddy_config:
