# Generated by Django 5.1.2 on 2025-01-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
