# Generated by Django 5.1.2 on 2025-01-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_remove_gamestate_score1_remove_gamestate_score2'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='game_id',
            field=models.IntegerField(default=1),
        ),
    ]
